"""Codegen for payload string secrecy (Phase 04 fix).
Reads src/payload/strings.list (ID = literal with \\r \\n escapes), emits
src/payload/strings.inc as XORed byte arrays. Consuming TUs contain ZERO
plaintext: MSVC persists constexpr-input literals in .rdata, so literals must
never appear in TU source at all. Keystream byte i: b ^ (0x5A + i*0x25).
Runtime twin: vacsafe::str::CopyTo in the generated header.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
LIST = ROOT / "src" / "payload" / "strings.list"
OUT = ROOT / "src" / "common" / "strings.inc"


def unescape(s):
    out = []
    i = 0
    while i < len(s):
        if s[i] == "\\" and i + 1 < len(s):
            n = s[i + 1]
            out.append({"r": "\r", "n": "\n", "t": "\t", "\\": "\\"}.get(n, n))
            i += 2
        else:
            out.append(s[i])
            i += 1
    return "".join(out)


def main():
    entries = []
    for line in LIST.read_text().splitlines():
        if not line.strip() or line.strip().startswith("#") or "=" not in line:
            continue
        name, val = line.split("=", 1)
        name = name.strip()
        # Format separator is exactly one space after '='; all other whitespace
        # (leading/trailing spaces, \r\n escapes) is significant content.
        if val.startswith(" "):
            val = val[1:]
        val = unescape(val)
        entries.append((name, val))
    blob = bytearray()
    ents = []
    for name, val in entries:
        raw = val.encode("latin1") + b"\x00"
        off = len(blob)
        for i, b in enumerate(raw):
            blob.append(b ^ ((0x5A + i * 0x25) & 0xFF))
        ents.append((name, off, len(raw) - 1))

    def hexarr(data):
        return ", ".join(f"0x{b:02X}" for b in data)

    L = []
    L.append("#pragma once")
    L.append("// GENERATED by tools/gen_strings.py from src/payload/strings.list. DO NOT EDIT.")
    L.append("// XOR keystream byte i: b ^ (0x5A + i*0x25). Plaintext lives only in")
    L.append("// strings.list (source-side); TUs see bytes. CRT-free, raw-path safe.")
    L.append("namespace vacsafe::str {")
    L.append("")
    L.append("enum Id : unsigned char {")
    for name, _, _ in ents:
        L.append(f"  SID_{name},")
    L.append("  SID_COUNT")
    L.append("};")
    L.append("")
    L.append(f"static const unsigned char kBlob[] = {{{hexarr(blob)}}};")
    L.append("struct Ent { unsigned off; unsigned char len; };")
    ent_s = ", ".join(f"{{{off},{ln}}}" for _, off, ln in ents)
    L.append(f"static const Ent kEnts[] = {{{ent_s}}};")
    L.append("")
    L.append("inline unsigned CopyTo(unsigned char id, char* dst, unsigned cap) {")
    L.append("  if (id >= (unsigned)SID_COUNT || !dst || !cap) return 0;")
    L.append("  const Ent& e = kEnts[id];")
    L.append("  unsigned n = 0;")
    L.append("  for (unsigned i = 0; i < e.len && n + 1 < cap; ++i)")
    L.append("    dst[n++] = (char)(kBlob[e.off + i] ^ (unsigned char)(0x5A + i * 0x25));")
    L.append("  dst[n] = 0;")
    L.append("  return n;")
    L.append("}")
    L.append("")
    L.append("// Wide-char variant for module names (PEB walks). No CRT (manual widen).")
    L.append("inline unsigned CopyToW(unsigned char id, wchar_t* dst, unsigned cap) {")
    L.append("  if (id >= (unsigned)SID_COUNT || !dst || !cap) return 0;")
    L.append("  const Ent& e = kEnts[id];")
    L.append("  unsigned n = 0;")
    L.append("  for (unsigned i = 0; i < e.len && n + 1 < cap; ++i)")
    L.append("    dst[n++] = (wchar_t)(kBlob[e.off + i] ^ (unsigned char)(0x5A + i * 0x25));")
    L.append("  dst[n] = 0;")
    L.append("  return n;")
    L.append("}")
    L.append("")
    L.append("} // namespace vacsafe::str")
    L.append("")
    OUT.write_text("\n".join(L))
    print(f"[ok] {len(ents)} strings, {len(blob)} bytes -> {OUT}")


main()
